[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vault = "JEJMHyemEsbq6oDwnmZGr5WmNRubu1vb1ESDpdCEjurE"
escrow = "Bk6mVT4NbK7Rdbqt6jGRjqTKD8RZ1aHX311sLQSx1fEy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
